Refactor/ifhelper improvements and ternary support
QuiltMC/quiltflower pull request #104
Opened 2022-05-02 18:00 UTC by Kroppeb

(Based on #103)

2022-05-02 18:00 UTC, Kroppeb commented
I probably should remove the unused branch in ternary coalescing.

2022-05-02 18:55 UTC, SuperCoder7979 commented
Where did the unused branch come from? Was it already in IfHelper or was it in TernaryProcessor?

2022-05-02 19:03 UTC, SuperCoder7979 requested changes
Looks good for the most part, but I have just a few comments for you to take a look at

2022-05-02 19:03 UTC, SuperCoder7979 commented on src/org/jetbrains/java/decompiler/modules/decompiler/StatEdge.java
> +  public void changeSource(Statement newSource) {
Seems like an improper merge?

2022-05-02 19:09 UTC, Kroppeb commented on src/org/jetbrains/java/decompiler/modules/decompiler/IfHelper.java
>    private static IfNode buildGraph(IfStatement stat, boolean stsingle) {
It's mostly explained in `IfNode` already.

2022-05-02 19:10 UTC, Kroppeb commented on src/org/jetbrains/java/decompiler/modules/decompiler/IfHelper.java
> +    static final int DIRECT = 0;
Coud do that, but then I might also want to change IfNode to just have 2 pairs of fields instead of 2 lists

2022-05-03 15:50 UTC, Kroppeb commented on src/org/jetbrains/java/decompiler/modules/decompiler/StatEdge.java
> +  public void changeSource(Statement newSource) {
Seems I managed to get GitHub to behave

2022-05-04 02:18 UTC, SuperCoder7979 requested changes
I have just a few more things for you to look at :)

2022-05-04 02:18 UTC, SuperCoder7979 commented on src/org/jetbrains/java/decompiler/modules/decompiler/IfHelper.java
> +        // remove weird successor
What's weird about the successor?

2022-05-04 02:18 UTC, SuperCoder7979 commented on src/org/jetbrains/java/decompiler/modules/decompiler/IfNode.java
> +import org.jetbrains.java.decompiler.modules.decompiler.stats.IfStatement;
Imports need to be moved above the comment

2022-05-04 03:48 UTC, merged