Make sure that block inlining doesn't cause validation to fail
QuiltMC/quiltflower pull request #116
Opened 2022-05-06 15:44 UTC by Kroppeb

2022-05-11 16:00 UTC, SuperCoder7979 requested changes
Hey, I just have one minor nitpick before merging :)

2022-05-12 03:02 UTC, Kroppeb commented on src/org/jetbrains/java/decompiler/modules/decompiler/InlineSingleBlockHelper.java
> +                throw new RuntimeException("Where have we been inlined to?");
The comment doesn't feel entirely correct. It's more like "no valid closure".

2022-05-12 03:11 UTC, SuperCoder7979 commented on src/org/jetbrains/java/decompiler/modules/decompiler/InlineSingleBlockHelper.java
> +                throw new RuntimeException("Where have we been inlined to?");
The idea was to make the comment more presentable, at least :P

2022-05-12 03:11 UTC, SuperCoder7979 approved these changes
Good now, thanks!

2022-05-12 03:11 UTC, merged