Make catch blocks aware of all assignments in the try blocks
QuiltMC/quiltflower pull request #138
Opened 2022-05-19 23:12 UTC by Kroppeb

2022-05-20 13:14 UTC, SuperCoder7979 requested changes
I have a few suggestions and lingering questions for this PR, but otherwise this is great!

2022-05-20 14:38 UTC, Kroppeb commented on src/org/jetbrains/java/decompiler/modules/decompiler/flow/DirectNode.java
> +    return this.successors.containsKey(type) && !this.successors.get(type).isEmpty();
`getSuccessors` does allocate an empty list if there is no list yet yet.

2022-05-20 14:38 UTC, Kroppeb commented on src/org/jetbrains/java/decompiler/modules/decompiler/flow/FlattenStatementsHelper.java
> +    if (!this.tryNodesStack.isEmpty()) {
That's currently being handled on [line 223](https://github.com/QuiltMC/quiltflower/pull/138/files#diff-8d96a692186ded9f7f28301b5ab815289ed3c2f7abdae8ea622778b29b72a4c0R223)

2022-05-20 14:38 UTC, Kroppeb commented on src/org/jetbrains/java/decompiler/modules/decompiler/flow/FlattenStatementsHelper.java
> +                // TODO: that ordering does not make sense
Not really, for `for (a : b)` you'd expect b to be the init statement.

2022-05-20 15:03 UTC, SuperCoder7979 commented on src/org/jetbrains/java/decompiler/modules/decompiler/flow/DirectNode.java
> +    return this.successors.containsKey(type) && !this.successors.get(type).isEmpty();
Fair. I was thinking that most nodes would have regular edges so it'd be faster, but most nodes probably won't have exception edges

2022-05-20 15:05 UTC, SuperCoder7979 commented on src/org/jetbrains/java/decompiler/modules/decompiler/flow/FlattenStatementsHelper.java
> +                // TODO: that ordering does not make sense
If you see DoStatement, you'll see that it's inverted there. DoStatement says in `for (a : b)` a is the init and b is the increment

2022-05-20 15:06 UTC, SuperCoder7979 commented on src/org/jetbrains/java/decompiler/modules/decompiler/sforms/SFormsConstructor.java
> +//        if (this.trackPhantomExitNodes && !mapTrueSource.isEmpty() && !mapNew.isEmpty()) { // FIXME: what for??
Forgot to add this in the review, but you should add a TODO here saying that we need to implement this at a later date, as discussed

2022-05-20 15:07 UTC, SuperCoder7979 commented on src/org/jetbrains/java/decompiler/modules/decompiler/flow/FlattenStatementsHelper.java
> +    if (!this.tryNodesStack.isEmpty()) {
I see, nice. A comment saying that's what it does would be good

2022-05-20 15:24 UTC, Kroppeb commented on src/org/jetbrains/java/decompiler/modules/decompiler/flow/FlattenStatementsHelper.java
> +                // TODO: that ordering does not make sense
Yeah, I know. But just like you said "it's inverted". IHMO I feel like they should be swapped. It just something that has been bugging me for a long time.

2022-05-20 15:25 UTC, SuperCoder7979 commented on src/org/jetbrains/java/decompiler/modules/decompiler/flow/FlattenStatementsHelper.java
> +                // TODO: that ordering does not make sense
That's fair, we should definitely fix it sometime

2022-05-28 11:57 UTC, SuperCoder7979 approved these changes
Looks good!

2022-05-28 11:57 UTC, merged