Fix issues with switch pattern statement consistency
QuiltMC/quiltflower pull request #198
Opened 2022-09-01 20:47 UTC by Kroppeb

2022-09-01 20:54 UTC, SuperCoder7979 requested changes
Minor code style tweak

2022-09-01 20:54 UTC, SuperCoder7979 commented on src/org/jetbrains/java/decompiler/modules/decompiler/SwitchPatternMatchProcessor.java
> +            findSuccessor:
Don't use labeled sequences, rather use booleans instead

2022-09-03 04:39 UTC, SuperCoder7979 approved these changes
LGTM now!

2022-09-03 10:48 UTC, l-Luna approved these changes
lgtm!

2022-09-03 14:06 UTC, merged