Add long option names & update help message
QuiltMC/quiltflower pull request #235
Opened 2022-12-28 04:38 UTC by sschr15

2022-12-28 04:58 UTC, ByMartrixx requested changes

2022-12-28 04:58 UTC, ByMartrixx commented on src/org/jetbrains/java/decompiler/main/extern/IFernflowerPreferences.java
>    @Name("Remove Bridge Methods")
The changes made here break any application that passes options to the BaseDecompiler constructor, like the Intellij plugin or Enigma

2022-12-28 04:58 UTC, ByMartrixx commented on src/org/jetbrains/java/decompiler/main/decompiler/OptionParser.java
> +    "--only=",
`--only=` isn't handled in `ConsoleDecompiler`

2022-12-28 21:54 UTC, ByMartrixx approved these changes
Looks good!

2023-02-03 15:18 UTC, Earthcomputer approved these changes
These changes are also good for the intellij plugin. I didn't like having to guess types

2023-03-29 16:35 UTC, jaskarth approved these changes
LGTM, tysm for doing this! The README needs to be updated, but that can be lower priority.

2023-03-29 16:35 UTC, merged