Refactor the way bytecode offsets are tracked.
QuiltMC/quiltflower pull request #389
Opened 2024-05-04 19:07 UTC by Kroppeb

* Instructions now track their own bytecode offsets.
* Split `SimpleInstructionSequence` and `FullInstructionSequence`. They aren't used in the same places and very little logic was actually shared.
* Renamed `SimpleInstructionSequence` to `InstructionSequence`
* Remove usages of `VBStyleCollection`
* Simplified and converted `ExceptionHandler` into a record

2024-08-17 00:21 UTC, jaskarth requested changes
I think this generally looks good but since this code is being significantly rewritten `FullInstructionSequence` and `InstructionSequence` need top level comments explaining what they are and how they're used.

2024-08-17 00:21 UTC, jaskarth commented on src/org/jetbrains/java/decompiler/struct/StructMethod.java
> +    FullInstructionSequence seq = new FullInstructionSequence(
Move back to one line

2025-07-08 13:10 UTC, Kroppeb commented
So many conflicts :panic:

2025-11-06 05:36 UTC, jaskarth approved these changes
Looks good, I merged it manually due to the commit mess that I caused earlier.

2025-11-06 05:36 UTC, closed without merging